name: Verify terraform module
description: "GitHub Action to run through the lifecycle for a terraform module: deploy, verify deploy, destroy, and verify destroy"
inputs:
  testcase:
    description: The identifier of the test case that should be applied
    required: true
  validateDeployScript:
    description: Script to validate deployment environment
    required: false
    default: ""
  testStagesDir:
    description: The directory where the test stages are located
    default: examples
    required: false
  testModuleDir:
    description: The directory where the current module will be copied
    default: module
    required: false
  workspace:
    description: The directory where the terraform workspace should be created
    default: /tmp/workspace
    required: false
  configBaseUrl:
    description: The base url where the terraform.tfvars file can be found for the test case. Expected to resolve to {configBaseUrl}/{testcase}/terraform.tfvars
    default: "https://raw.githubusercontent.com/ibm-garage-cloud/action-module-verify/main/env"
    required: false
  testPlan:
    description: Flag indicating that the plan should be tested after the apply to ensure there are no changes
    default: "false"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup ${{ inputs.testcase }} terraform.tfvars
      id: setup-terraform
      shell: bash
      run: |
        echo "*** Setup ${{ inputs.testcase }} terraform.tfvars ***"

        path=$(echo "${{ inputs.testModuleDir }}" | sed -E "s~[^/]+~..~g")
        cd "${{ inputs.testStagesDir }}"

        NAMESPACE=$(echo "${GITHUB_REPOSITORY}" | sed -E "s~.*/~~g" | sed -E "s/terraform-//g")

        echo "++ Retrieving terraform.tfvars from ${{ inputs.configBaseUrl }}/${{ inputs.testcase }}/terraform.tfvars"

        if curl -sL ${{ inputs.configBaseUrl }}/${{ inputs.testcase }}/terraform.tfvars 1> /dev/null; then
          curl -Lo terraform.tfvars ${{ inputs.configBaseUrl }}/${{ inputs.testcase }}/terraform.tfvars
          
          TFVARS_CONTENT=$(cat terraform.tfvars)
          if [[ "${TFVARS_CONTENT}" == "404: Not Found" ]]; then
            echo "Terraform config not found"
            echo "" > terraform.tfvars
          fi
        else
          echo "No terraform.tfvars file found"
          echo "" > terraform.tfvars
        fi
        echo "namespace=\"${NAMESPACE}\"" >> terraform.tfvars

        echo "++ terraform.tfvars"
        cat terraform.tfvars

        echo "::set-output name=namespace::$NAMESPACE"

    # Deploy
    - name: Deploy ${{ inputs.testcase }}
      shell: bash
      run: |
        echo "*** Deploy ${{ inputs.testcase }} ***"

        if [[ -f .env ]]; then
          echo "++ Loading config from .env file"
          source .env
        fi

        cd "${{ inputs.testStagesDir }}"
        export REPO_NAME="${{ github.event.repository.name }}"
        echo "Repository: $REPO_NAME"
        $GITHUB_ACTION_PATH/scripts/apply.sh || exit 1
        
        if [[ "${{ inputs.testPlan }}" == "true" ]]; then
          echo "Testing plan after apply"
          terraform plan -detailed-exitcode
        fi

    # Test deploy
    - name: Validate deploy ${{ inputs.testcase }}
      shell: bash
      run: |
        echo "*** Validate deploy ${{ inputs.testcase }} ***"

        if [[ -f .env ]]; then
          echo "++ Loading config from .env file"
          source .env
        fi

        ROOT_DIR="$PWD"

        cd "${{ inputs.testStagesDir }}"
        $GITHUB_ACTION_PATH/scripts/validate-deploy.sh ${{ inputs.testcase }} ${{ steps.setup-terraform.outputs.namespace }} "${CONSOLE_LINK_NAME}" "$ROOT_DIR/${{ inputs.validateDeployScript }}"
